language: java
jdk: openjdk8

front:
  - build
  - test

jobs:
  include:
    - stage: build
      name: Docker frontend image build
      services:
        - docker
      script:
        - cd vboard-front
        - docker build .
    - stage: build
      name: Docker backend image build
      services:
        - docker
      script:
        - cd vboard-ws
        - docker build .
    - stage: test
      name: Pre-commit checks
      script:
        # Installing pre-commit globally fails with:
        # Installing collected packages: aspy.yaml, cached-property, identify, nodeenv, pre-commit
        #   File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
        #     with open(dst, 'wb') as fdst:
        # IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/aspy.yaml-1.0.0-nspkg.pth'
        - pip install --user pre-commit && pre-commit run --all-files
    - stage: test
      name: Backend unit tests & linter
      env:
        global:
          # Avoid hitting Travis CI max log size limit:
          - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      script:
        - cd vboard-ws
        - mvn --version
        - mvn verify
    - stage: test
      name: Frontend linters
      script:
        - cd vboard-front
        - nvm use stable
        - npm --version
        - npm install
        - npm run lint

cache:
  pip: true
  directories:
  - $HOME/.m2    # Maven packages
