language: java
jdk: openjdk8

front:
  - lint
  - build
  - test

jobs:
  include:
    - stage: lint
      name: Hadolint Dockerfiles
      env:
        HADOLINT: "${HOME}/hadolint"
      install:
        - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}
      script:
        - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
    - stage: lint
      name: Pre-commit checks
      script:
        - pip install --user pre-commit && pre-commit run --all-files
    - stage: build
      name: Docker frontend image build
      services:
        - docker
      script:
        - cd vboard-front
        - docker build .
    - stage: build
      name: Docker backend image build
      services:
        - docker
      script:
        - cd vboard-ws
        - docker build .
    - stage: test
      name: Backend unit tests & linter
      env:
        global:
          # Avoid hitting Travis CI max log size limit:
          - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      script:
        - cd vboard-ws
        - mvn --version
        - mvn verify
    - stage: test
      name: Frontend linters
      script:
        - cd vboard-front
        - nvm use stable
        - npm --version
        - npm install
        - npm run lint

cache:
  pip: true
  directories:
  - $HOME/.m2    # Maven packages
