application:
  version: DEV

logging:
  level:
    org.springframework.web: DEBUG
    com.vsct.vboard: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vboard_pins
    username: root
    password: root
elasticsearch:
  serverUri: http://localhost:9200

server:
  error:
    whitelabel:
      enabled: true
endpoints:
  enabled: true
  sensitive: false
management:
  security:
    enabled: false

uploads:
  imagesStorageDirectory: imagesStorageDir
  blogImagesDirectory: blogImagesDir
  multiplePinsPerUrlAllowed: false
emails:
  hostname: dummy
